[dependencies]
map9 = "https://github.com/ZhenyaUsenko/motoko-hash-map#v9.0.1@10b68f6ea8df5e72dfa4c07a50c8bb60a916c233"
map = "9.0.1"
vector = "0.4.0"
star = "0.1.1"
icrc1-mo = "0.0.15"
candy = "0.3.1"
stableheapbtreemap = "1.5.0"
ovs-fixed = "0.1.2"
timer-tool = "0.1.1"
ic-certification = "0.1.3"
rep-indy-hash = "0.1.1"
class-plus = "0.0.1"
base = "0.14.4"

[dev-dependencies]
test = "2.0.0"
fuzz = "0.2.1"

[package]
name = "icrc75-mo"
version = "0.2.0"
description = "icrc75 for motoko"
repository = "https://github.com/icdevsorg/icrc75.mo"
keywords = [ "icrc75", "lists", "rbac" ]
