dev-dependencies = { }

[dependencies]
base = "0.11.1"
map9 = "https://github.com/ZhenyaUsenko/motoko-hash-map#v9.0.1@10b68f6ea8df5e72dfa4c07a50c8bb60a916c233"
map = "9.0.1"
vector = "0.2.0"
star = "0.1.1"
icrc1-mo = "0.0.15"
candy = "0.3.0"
stableheapbtreemap = "1.5.0"
"ovs-fixed" = "https://github.com/icdevsorg/ovs-fixed#v0.1.1"

[package]
name = "icrc75-mo"
version = "0.0.1"
description = "icrc75 for motoko"
repository = "https://github.com/PanIndustrial-Org/icrc75.mo"
keywords = [ "icrc75", "lists", "rbac" ]
